name: stratified_nmf
dependencies:
  - python=3.11.5
  - pip
  - pip:
    - matplotlib==3.8.1
    - numpy==1.26.2
    - pandas==2.1.3
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - seaborn==0.13.0
    - torch==2.1.0
    - torchvision==0.16.0
    - termcolor==2.3.0
    - tqdm==4.66.1
